language : python

python:
  - "3.7"

git:
  depth: 1

env:
  -SECRET_KEY='TEST' DEBUG=False

install:
  -pip install requirements.txt

# script to run tests. Script can have many commands, one per line.
script:
  - coverage run --source='.' manage.py test
after_script:
  - bash <(curl -s https://codecov.io/bash)
