# Generated by Django 3.2.8 on 2021-10-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0002_calendartag'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skdue_calendar.calendartag'),
            preserve_default=False,
        ),
    ]
