# Generated by Django 3.2.8 on 2021-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0005_followstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.TextField(max_length=32)),
            ],
        ),
    ]
