# Generated by Django 3.2.8 on 2021-10-30 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0006_calendartagtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartag',
            name='tag_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skdue_calendar.calendartagtype'),
            preserve_default=False,
        ),
    ]
