# Generated by Django 3.2.8 on 2021-11-10 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skdue_calendar.models.user_setting


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skdue_calendar', '0007_calendartag_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartag',
            name='tag_color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=skdue_calendar.models.user_setting.nameFile)),
                ('about', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
