# Generated by Django 3.2.6 on 2021-11-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0008_auto_20211110_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='followstatus',
            name='followed_calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followed_calendar', to='skdue_calendar.calendar'),
        ),
        migrations.AddField(
            model_name='followstatus',
            name='user_calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_calendar', to='skdue_calendar.calendar'),
        ),
    ]
