# Generated by Django 3.2.6 on 2021-11-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0009_auto_20211115_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followstatus',
            name='user_calendar',
        ),
    ]
