# Generated by Django 3.2.9 on 2021-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skdue_calendar', '0009_auto_20211116_0323'),
        ('skdue_calendar', '0010_remove_followstatus_user_calendar'),
    ]

    operations = [
    ]
