# Generated by Django 3.2.9 on 2021-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('token', models.TextField(max_length=2000)),
            ],
        ),
    ]
