# Generated by Django 3.2.9 on 2021-11-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='linked_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
