name: Django

on:
  push:
    branches:
      - dev
      - main
      - apply-action

  pull_request:
    branches:
      - dev
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - env :
      SECRET_KEY='TEST'
      DEBUG=False 
      ALLOWED_HOSTS='*'
      CORS_ALLOWED_ORIGINS='https://*'
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
